import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="w-full p-3 bg-[#1F2228] rounded flex flex-row items-center justify-between">
        <div className="flex flex-row items-center">
          <div className="text-white w-fit pr-4 border-r border-headerBorderColor">
            CRM
          </div>
          <div className="pl-4 text-white">Contacts</div>
        </div>
        <div>SEARCH</div>
      </header>
    </>
  );
}
